security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

        discord_user_provider:
            id: App\Security\DiscordUserProvider

    firewalls:
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true

            custom_authenticators:
                - App\Security\DiscordAuthenticator

            logout:
                path: app_logout

    access_control:
        - { path: ^/connect/discord, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect/discord/check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connexion, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/inscription, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/panel, roles: ROLE_EVENTS }
        - { path: ^/admin/event, roles: ROLE_EVENTS }
