parameters:
    twitch.client_id: '%env(TWITCH_CLIENT_ID)%'
    twitch.client_secret: '%env(TWITCH_CLIENT_SECRET)%'

services:
    App\Service\TwitchService:
        arguments:
            $client: '@http_client'
            $clientId: '%twitch.client_id%'
            $clientSecret: '%twitch.client_secret%'
            $cache: '@cache.app'
        public: true

    App\Security\DiscordAuthenticator:
        arguments:
            $clientRegistry: '@knpu.oauth2.registry'
            $router: '@router'
            $userProvider: '@App\Security\DiscordUserProvider'

    App\Security\DiscordUserProvider:
        arguments: []

    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $clientId: '%twitch.client_id%'
            $clientSecret: '%twitch.client_secret%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests.php'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
